# Docker Compose for local development
version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DRUGINSIGHTAI_ENVIRONMENT=development
      - DRUGINSIGHTAI_DATABASE_URL=postgresql://druginsightai:changeme@postgres:5432/druginsightai
      - DRUGINSIGHTAI_REDIS_URL=redis://redis:6379/0
      - DRUGINSIGHTAI_ENABLE_LOCAL_AUTH=true
      - DRUGINSIGHTAI_ENABLE_AWS_AUTH=false
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./src:/app/src
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - druginsightai-network

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: druginsightai
      POSTGRES_USER: druginsightai
      POSTGRES_PASSWORD: changeme
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U druginsightai -d druginsightai"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - druginsightai-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - druginsightai-network

volumes:
  postgres_data:
  redis_data:

networks:
  druginsightai-network:
    driver: bridge
